<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CodeIgniter Application Test Suite" tests="36" assertions="42" failures="10" errors="8" time="4.641277">
    <testsuite name="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" fullPackage="Lapangan" tests="14" assertions="24" failures="4" errors="0" time="1.483781">
      <testcase name="test_index" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="21" assertions="3" time="0.118411"/>
      <testcase name="test_sewajadwal" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="29" assertions="3" time="0.089155"/>
      <testcase name="test_sewajadwal_gagal" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="37" assertions="1" time="0.089033"/>
      <testcase name="test_detail" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="43" assertions="3" time="0.132071"/>
      <testcase name="test_inputsewa" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="49" assertions="3" time="0.097401"/>
      <testcase name="test_inputsewa_gagal" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="57" assertions="1" time="0.097615"/>
      <testcase name="test_signup" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="64" assertions="1" time="0.122606"/>
      <testcase name="test_ceklogin" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="69" assertions="1" time="0.135465"/>
      <testcase name="test_login_sukses" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="79" assertions="0" time="0.126466">
        <failure type="PHPUnit_Framework_AssertionFailedError">Lapangan_test::test_login_sukses
redirect() is not called.

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:407
C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php:82
</failure>
      </testcase>
      <testcase name="test_login_gagal" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="84" assertions="3" time="0.103282"/>
      <testcase name="test_login_gagal_password" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="93" assertions="1" time="0.092211">
        <failure type="PHPUnit_Framework_ExpectationFailedException">Lapangan_test::test_login_gagal_password
URL to redirect is not Redirect to http://localhost/GIT/index.php/lapangan/index/fail but Redirect to http://localhost/GIT/lapangan/login.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Redirect to http://localhost/GIT/index.php/lapangan/index/fail
+Redirect to http://localhost/GIT/lapangan/login

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:427
C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php:99
</failure>
      </testcase>
      <testcase name="test_login_gagal_username" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="103" assertions="1" time="0.094561">
        <failure type="PHPUnit_Framework_ExpectationFailedException">Lapangan_test::test_login_gagal_username
URL to redirect is not Redirect to http://localhost/GIT/index.php/lapangan/index/fail but Redirect to http://localhost/GIT/lapangan/login.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Redirect to http://localhost/GIT/index.php/lapangan/index/fail
+Redirect to http://localhost/GIT/lapangan/login

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:427
C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php:109
</failure>
      </testcase>
      <testcase name="test_APPPATH" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="139" assertions="1" time="0.051815"/>
      <testcase name="test_logout" class="Lapangan_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php" line="150" assertions="2" time="0.133689">
        <failure type="PHPUnit_Framework_ExpectationFailedException">Lapangan_test::test_logout
URL to redirect is not Redirect to http://localhost/GIT/index.php/lapangan but Redirect to http://localhost/GIT/lapangan/login.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Redirect to http://localhost/GIT/index.php/lapangan
+Redirect to http://localhost/GIT/lapangan/login

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:427
C:\xampp\htdocs\GIT\application\tests\controllers\Lapangan_test.php:162
</failure>
      </testcase>
    </testsuite>
    <testsuite name="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" fullPackage="Welcome" tests="22" assertions="18" failures="6" errors="8" time="3.157495">
      <testcase name="test_index" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="19" assertions="1" time="0.121274"/>
      <testcase name="test_ceklogin" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="25" assertions="1" time="0.142435"/>
      <testcase name="test_ceklogin_admin_not_login_kosongsemua" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="35" assertions="1" time="0.115408">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_ceklogin_admin_not_login_kosongsemua
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:42
</error>
      </testcase>
      <testcase name="test_ceklogin_admin_not_login_nopassword" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="45" assertions="1" time="0.126657">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_ceklogin_admin_not_login_nopassword
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:52
</error>
      </testcase>
      <testcase name="test_ceklogin_admin_not_login_nousername" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="55" assertions="1" time="0.117712">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_ceklogin_admin_not_login_nousername
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:62
</error>
      </testcase>
      <testcase name="test_ceklogin_admin_not_login_unmatch" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="65" assertions="1" time="0.110947">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_ceklogin_admin_not_login_unmatch
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:72
</error>
      </testcase>
      <testcase name="test_login" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="75" assertions="1" time="0.118725"/>
      <testcase name="test_logout" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="80" assertions="1" time="0.190828">
        <failure type="PHPUnit_Framework_AssertionFailedError">Welcome_test::test_logout
redirect() is not called.

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:407
C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:89
</failure>
      </testcase>
      <testcase name="test_inputlapangan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="92" assertions="2" time="0.187455"/>
      <testcase name="test_no_inputlapangan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="104" assertions="0" time="0.107413">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_no_inputlapangan
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:106
</error>
      </testcase>
      <testcase name="test_dahboard" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="109" assertions="1" time="0.143408"/>
      <testcase name="test_datapenyewaan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="114" assertions="1" time="0.151473"/>
      <testcase name="test_tambahlapangan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="119" assertions="1" time="0.115750">
        <failure type="PHPUnit_Framework_ExpectationFailedException">Welcome_test::test_tambahlapangan
Failed asserting that 'Array
(
    [error] =&gt; &lt;p&gt;You did not select a file to upload.&lt;/p&gt;
)
1' contains "&lt;th&gt;NO&lt;/th&gt;".

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:121
</failure>
      </testcase>
      <testcase name="test_editData" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="124" assertions="1" time="0.144134"/>
      <testcase name="test_datalapangan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="129" assertions="2" time="0.183268"/>
      <testcase name="test_not_datalapangan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="141" assertions="0" time="0.103351">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_not_datalapangan
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:143
</error>
      </testcase>
      <testcase name="test_deleteData" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="146" assertions="1" time="0.229831">
        <failure type="PHPUnit_Framework_AssertionFailedError">Welcome_test::test_deleteData
redirect() is not called.

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:407
C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:155
</failure>
      </testcase>
      <testcase name="test_deleteDataLapangan" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="158" assertions="0" time="0.132047">
        <failure type="PHPUnit_Framework_AssertionFailedError">Welcome_test::test_deleteDataLapangan
redirect() is not called.

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:407
C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:160
</failure>
      </testcase>
      <testcase name="test_validasi" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="163" assertions="0" time="0.139949">
        <failure type="PHPUnit_Framework_AssertionFailedError">Welcome_test::test_validasi
redirect() is not called.

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:407
C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:165
</failure>
      </testcase>
      <testcase name="test_no_validasi" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="168" assertions="0" time="0.128259">
        <failure type="PHPUnit_Framework_AssertionFailedError">Welcome_test::test_no_validasi
redirect() is not called.

C:\xampp\htdocs\GIT\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php:407
C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:170
</failure>
      </testcase>
      <testcase name="test_do_editData" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="173" assertions="1" time="0.206598">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_do_editData
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:182
</error>
      </testcase>
      <testcase name="test_do_editData_failed" class="Welcome_test" file="C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php" line="185" assertions="0" time="0.140573">
        <error type="PHPUnit_Framework_Exception">Welcome_test::test_do_editData_failed
PHPUnit_Framework_Exception: Argument #2 of PHPUnit_Framework_Assert::assertContains() must be a array, iterator or string

C:\xampp\htdocs\GIT\application\tests\controllers\Welcome_test.php:187
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
